<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
      DB::table('productos')->insert([
    // 🍺 Bebidas Alcohólicas → Proveedor: Bavaria (1)
    [
        'nombre' => 'Copa de aguardiente',
        'descripcion' => 'Shot de aguardiente tradicional.',
        'precio' => 3500.00,
        'stock' => 50,
        'idproveedor' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Ron Caldas 1 copa',
        'descripcion' => 'Copa de Ron Caldas.',
        'precio' => 4000.00,
        'stock' => 50,
        'idproveedor' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Poquerón de Poker',
        'descripcion' => 'Cerveza Poker tamaño grande.',
        'precio' => 9000.00,
        'stock' => 50,
        'idproveedor' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Coronita',
        'descripcion' => 'Botella pequeña de Corona.',
        'precio' => 5000.00,
        'stock' => 50,
        'idproveedor' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Corona',
        'descripcion' => 'Cerveza Corona.',
        'precio' => 10000.00,
        'stock' => 50,
        'idproveedor' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Lightning',
        'descripcion' => 'Bebida alcohólica tipo Ice.',
        'precio' => 4000.00,
        'stock' => 50,
        'idproveedor' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Heineken',
        'descripcion' => 'Cerveza premium Heineken.',
        'precio' => 5000.00,
        'stock' => 50,
        'idproveedor' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Costeña Bacana',
        'descripcion' => 'Cerveza Costeña Bacana.',
        'precio' => 3500.00,
        'stock' => 50,
        'idproveedor' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Costeña',
        'descripcion' => 'Cerveza Costeña tradicional.',
        'precio' => 3000.00,
        'stock' => 50,
        'idproveedor' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Media de aguardiente',
        'descripcion' => 'Media botella de aguardiente.',
        'precio' => 40000.00,
        'stock' => 20,
        'idproveedor' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Media de ron',
        'descripcion' => 'Media botella de ron.',
        'precio' => 44000.00,
        'stock' => 20,
        'idproveedor' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Cóctel Los Cuates',
        'descripcion' => 'Cóctel de la casa.',
        'precio' => 5000.00,
        'stock' => 50,
        'idproveedor' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Cola y Pola',
        'descripcion' => 'Mezcla de cerveza y gaseosa.',
        'precio' => 3500.00,
        'stock' => 50,
        'idproveedor' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Budweiser',
        'descripcion' => 'Cerveza Budweiser.',
        'precio' => 4000.00,
        'stock' => 50,
        'idproveedor' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Six Pack Cola y Pola',
        'descripcion' => 'Combo de 6 cervezas Cola y Pola.',
        'precio' => 21000.00,
        'stock' => 20,
        'idproveedor' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],


    // ☕ Calientes → Proveedor: Postobón = 3 (asumido)
    [
        'nombre' => 'Café',
        'descripcion' => 'Tinto caliente.',
        'precio' => 1500.00,
        'stock' => 50,
        'idproveedor' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Aromática',
        'descripcion' => 'Aromática de hierbas.',
        'precio' => 1500.00,
        'stock' => 50,
        'idproveedor' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],


    // 🥤 Gaseosas y refrescos → CocaCola (2) y Postobón (3)
    [
        'nombre' => 'Coca Cola',
        'descripcion' => 'Bebida gaseosa',
        'precio' => 0.00,
        'stock' => 50,
        'idproveedor' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Coca Cola 350 ml',
        'descripcion' => 'Presentación personal',
        'precio' => 3500.00,
        'stock' => 50,
        'idproveedor' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Coca Cola personal',
        'descripcion' => 'Presentación pequeña',
        'precio' => 2500.00,
        'stock' => 50,
        'idproveedor' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Coca Cola 500 ml',
        'descripcion' => 'Botella mediana',
        'precio' => 4000.00,
        'stock' => 50,
        'idproveedor' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Coca Cola 1.5 L',
        'descripcion' => 'Botella grande',
        'precio' => 9000.00,
        'stock' => 20,
        'idproveedor' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Gaseosa 250 ml',
        'descripcion' => 'Gaseosa personal',
        'precio' => 2500.00,
        'stock' => 50,
        'idproveedor' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Gaseosa 350 ml',
        'descripcion' => 'Gaseosa mediana',
        'precio' => 3500.00,
        'stock' => 50,
        'idproveedor' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Soda Plástica',
        'descripcion' => 'Bebida saborizada carbonatada.',
        'precio' => 4000.00,
        'stock' => 50,
        'idproveedor' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Soda Bretaña',
        'descripcion' => 'Soda transparente.',
        'precio' => 3500.00,
        'stock' => 50,
        'idproveedor' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],


    // 💧 Aguas → Postobón (3)
    [
        'nombre' => 'Agua pequeña',
        'descripcion' => 'Agua embotellada 300ml.',
        'precio' => 2000.00,
        'stock' => 50,
        'idproveedor' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Agua grande',
        'descripcion' => 'Agua embotellada 600ml.',
        'precio' => 4000.00,
        'stock' => 50,
        'idproveedor' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Agua saborizada',
        'descripcion' => 'Agua con sabor.',
        'precio' => 4000.00,
        'stock' => 50,
        'idproveedor' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],


    // 🧃 Jugos y energéticas → Postobón y CocaCola
    [
        'nombre' => 'Jugo del Valle',
        'descripcion' => 'Jugo de fruta.',
        'precio' => 4000.00,
        'stock' => 50,
        'idproveedor' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Red Bull',
        'descripcion' => 'Bebida energética.',
        'precio' => 8000.00,
        'stock' => 30,
        'idproveedor' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Jugos Hit caja',
        'descripcion' => 'Jugo en caja.',
        'precio' => 3000.00,
        'stock' => 50,
        'idproveedor' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Jugos Hit vidrio 250 ml',
        'descripcion' => 'Jugo en botella de vidrio.',
        'precio' => 3500.00,
        'stock' => 50,
        'idproveedor' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Electrolit',
        'descripcion' => 'Hidratante.',
        'precio' => 6000.00,
        'stock' => 30,
        'idproveedor' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Gatorade',
        'descripcion' => 'Bebida hidratante.',
        'precio' => 4000.00,
        'stock' => 50,
        'idproveedor' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Vive 100',
        'descripcion' => 'Energizante.',
        'precio' => 5000.00,
        'stock' => 50,
        'idproveedor' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],


    // 🍿 Snacks → FritoLay (4)
    [
        'nombre' => 'Trident x5',
        'descripcion' => 'Paquete con 5 chicles.',
        'precio' => 2000.00,
        'stock' => 50,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Trident x3',
        'descripcion' => 'Paquete con 3 chicles.',
        'precio' => 1000.00,
        'stock' => 50,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Trident pequeño x4',
        'descripcion' => 'Mini paquete de chicles.',
        'precio' => 600.00,
        'stock' => 50,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Trident x18',
        'descripcion' => 'Paquete grande de chicles.',
        'precio' => 5000.00,
        'stock' => 50,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Barra Halls',
        'descripcion' => 'Dulce mentolado.',
        'precio' => 3500.00,
        'stock' => 50,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Halls unidad',
        'descripcion' => 'Caramelo individual.',
        'precio' => 500.00,
        'stock' => 100,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // Galletas y Maní
    [
        'nombre' => 'Chokis',
        'descripcion' => 'Galletas con chispas de chocolate.',
        'precio' => 2500.00,
        'stock' => 50,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Maní Moto',
        'descripcion' => 'Maní en diferentes sabores.',
        'precio' => 3000.00,
        'stock' => 50,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Maní con arándanos',
        'descripcion' => 'Snack de maní con arándanos.',
        'precio' => 3000.00,
        'stock' => 50,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Galleta Festival x8',
        'descripcion' => 'Paquete con 8 galletas Festival.',
        'precio' => 2500.00,
        'stock' => 50,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // Pasabocas
    [
        'nombre' => 'De Todito mediano',
        'descripcion' => 'Pasabocas tamaño mediano.',
        'precio' => 7000.00,
        'stock' => 50,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'De Todito grande',
        'descripcion' => 'Pasabocas tamaño grande.',
        'precio' => 4000.00,
        'stock' => 50,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'De Todito gigante',
        'descripcion' => 'Pasabocas tamaño gigante.',
        'precio' => 9000.00,
        'stock' => 30,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Doritos pequeños',
        'descripcion' => 'Paquete pequeño de Doritos.',
        'precio' => 4000.00,
        'stock' => 50,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Doritos medianos',
        'descripcion' => 'Paquete mediano de Doritos.',
        'precio' => 7000.00,
        'stock' => 50,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Doritos grandes',
        'descripcion' => 'Paquete grande de Doritos.',
        'precio' => 9000.00,
        'stock' => 30,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Choclitos pequeños',
        'descripcion' => 'Pasabocas de maíz.',
        'precio' => 3500.00,
        'stock' => 50,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Cheetos pequeños',
        'descripcion' => 'Pasabocas de queso.',
        'precio' => 3500.00,
        'stock' => 50,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Chees Tris',
        'descripcion' => 'Pasabocas sabor queso.',
        'precio' => 3500.00,
        'stock' => 50,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Papas Margarita',
        'descripcion' => 'Papas de múltiples sabores.',
        'precio' => 4000.00,
        'stock' => 50,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Papas pobres',
        'descripcion' => 'Snack económico.',
        'precio' => 3000.00,
        'stock' => 50,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Chicharrón',
        'descripcion' => 'Pasabocas de chicharrón.',
        'precio' => 3000.00,
        'stock' => 50,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nombre' => 'Plátanos',
        'descripcion' => 'Pasabocas de plátano.',
        'precio' => 3000.00,
        'stock' => 50,
        'idproveedor' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],


            
        ]);
    }
}
